services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'

volumes:
  keycloak_data:
